ARCH_ALLROUNDER = 0
ARCH_LATEBOOSTER = 1
ARCH_TOPSPEED = 2
ARCH_COMBAT = 3
ARCH_DRIFT = 4
ARCH_OMNIROUNDER = 5
ARCH_SUPERSONIC = 6
ARCH_BOOST = 7
ARCH_TRICKSTER = 8
ARCH_NONE = 9

ARCH_ID_TO_NAME = {
    ARCH_ALLROUNDER: "All-Rounder",
    ARCH_LATEBOOSTER: "Late Booster",
    ARCH_TOPSPEED: "Top Speed",
    ARCH_COMBAT: "Combat",
    ARCH_DRIFT: "Drift",
    ARCH_OMNIROUNDER: "Omnirounder",
    ARCH_SUPERSONIC: "Super Sonic",
    ARCH_BOOST: "Boost",
    ARCH_TRICKSTER: "Trickster",
    ARCH_NONE: "None",
}
ALL_TE_ARCHS = list(ARCH_ID_TO_NAME.keys())